// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWordGenerator.Database;

namespace TestWordGenerator.Migrations
{
    [DbContext(typeof(HashingContext))]
    partial class HashingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWordGenerator.Database.PasswordHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HashSha256")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashSha384")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashSha512")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordHashes");
                });

            modelBuilder.Entity("TestWordGenerator.Database.ProcessingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NextPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NoOfProcessedPasswords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ProcessingInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
